- hosts: localhost
  vars: 
    
      lnx_install_date: 28
      lnx_php_installed_version: 2.0.8
  tasks:
    - include_role:
          name: json_variables
      vars:
        set: yes
        json_variables:
            lnx_install_date: "{{ lnx_install_date }}"
            lnx_php_installed_version: "{{ lnx_php_installed_version }}"
    - debug: var=existing_lnx_install_date
